import Head from 'next/head'
import React, { FormEvent, useState } from 'react'
import { useLogin } from '../hooks/useLogin';
import { useCookies } from 'react-cookie';
import { useRouter } from 'next/router';

export default function Home() {

  const [email, setEmail] = useState("")
  const [mdp, setMdp] = useState("")
  const [cookies, setCookie] = useCookies();

  const [login] = useLogin();

  const router = useRouter();

  const handleSubmit = async (e: FormEvent<HTMLFormElement>): Promise<void> =>{
    e.preventDefault();
    

    const {data: {authLogin: user}} = await login({variables: {username: email, password: mdp}})

    console.log(user)

    if(!user){
      throw Error('Impossible de récupérer les informations de connexion')
    }

    (setCookie('user', user));

    router.push('/user/dashboard')
  }


  return (
    <div className="flex flex-col items-center justify-center min-h-screen py-2 bg-gray-500">
      <Head>
        <title>Post Mortem Chest</title>
        <meta name="description" content="Generated by Post Mortem Chest" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
        <h1 className="text-white text-6xl mb-11">
          Post Mortem Chest
        </h1>
        <div className="bg-white rounded-2xl shadow-2xl flex flex-row w-2/3 max-w-4xl">
            {/* SIGN IN DIV */}
            <div className="w-3/5 p-5">
              <div className="text-left font-bold">
                Post Mortem Chest
              </div>
              <div className="py-10">
                  <h2 className="text-3xl font-bold mb-2">Connectez-vous !</h2>
                  <div className="border-2 w-10 border-emerald-500 inline-block mb-2"></div>
              </div>
              <form onSubmit={handleSubmit}>
                <div className="flex flex-col items-center">
                  <div className="bg-gray-100 w-64 p-2 flex items-center rounded-xl mb-3 ">
                    <input type="email" name="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="Email" className="bg-gray-100 outline-none flex-1 m-2"/>
                  </div>
                  <div className="bg-gray-100 w-64 p-2 flex items-center rounded-xl mb-3">
                    <input type="password" name="password" value={mdp} onChange={e => setMdp(e.target.value)} placeholder="Mot de passe" className="bg-gray-100 outline-none flex-1 m-2"/>
                  </div>
                  <div className="flex w-64 mb-5">
                    <label className="flex items-center text-xs"> 
                      <input type="checkbox" name="remember" className="mr-1"/>Se souvenir de moi
                    </label>
                  </div>
                  <button className="border-2 border-emerald-500 rounded-full px-12 py-2 inline-block font-bold hover:bg-emerald-500 hover:text-white">Connexion</button>
                  </div>
              </form>
            </div>
          {/* SIGN UP DIV */}
          <div className="w-2/5 bg-emerald-500 text-white rounded-tr-2xl rounded-br-2xl py-36 px-12">
            <h2 className="text-3xl font-bold mb-2">Enregistre-toi !</h2>
            <div className="border-2 w-10 text-white inline-block mb-2"></div>
            <p className="mb-10">Tu es un défunt en devenir ?! N&apos;attends plus et loue de ce pas un coffre fort pour tes fichiers et photos que tu souhaiterais laisser sur Terre !</p>
            <a href="signUp" className="border-2 border-white rounded-full px-12 py-2 inline-block font-bold hover:bg-white hover:text-emerald-500">S&apos;inscrire</a>
          </div>
        </div>
      </main>
    </div>
  )
}
